server:
  port: port
  debug: true
  read_timeout_seconds: 300
  write_timeout_seconds: 300

application:
  min_password_strength: 0
  swagger_ui_path: third_party/swaggerui/dist

keycloaks:
  realm: BNI
  client_secret: 63362870-38d1-4a51-9768-678d2b8e10bf
  cliend_id: labs-app
  server: http://localhost:port
  user_admin: admin
  pass_admin: admin
  realm_admin: master

database:
  dialect: mysql
  user: demo
  password: demo
  name: demo_microservice
  protocol: tcp
  host: demo.us-east-2.compute.amazonaws.com
  port: port
  settings: tls=skip-verify&charset=utf8&parseTime=True&loc=Local&autocommit=true&timeout=20s
